cuervolu/cortex

- apps/desktop/package.json
- apps/frontend/package.json
- package.json
- packages/shared/package.json
- pnpm-lock.yaml
- Move shared dependencies to the root package.json
- Remove duplicated dependencies from subprojects (frontend, desktop, shared)
- Update pnpm workspace overrides to ensure consistent versions across the monorepo
- Improve dependency management and reduce redundancy in the project structure
> refactor(app): centralize common dependencies in root package.json

- apps/desktop/src/components/roadmap/RoadmapList.vue
- apps/desktop/src/layouts/default.vue
- apps/desktop/src/pages/index.vue
- apps/desktop/src/pages/profile.vue
- apps/desktop/src/pages/roadmap/[slug]/courses/[slug].vue
- apps/desktop/src/pages/roadmap/[slug]/index.vue
- apps/desktop/src/pages/roadmap/index.vue
- apps/desktop/src/pages/settings.vue
###
**Description:**
This pull request addresses the margin issue in the content section of the desktop app. The changes implemented fix the spacing to improve the overall visual appearance and alignment.
> Arreglo de margen en el apartado de contenido de la app de escritorio

- scripts/initialize/lesson_content/leccion-1-Los-super-heroes-rust.md
- scripts/initialize/lesson_content/leccion-1-Preparando-la-Cafetera.md
- scripts/initialize/lesson_content/leccion-1-go-la-ardilla-amigable.md
- scripts/initialize/lesson_content/leccion-2-Aventuras-con-rust.md
- scripts/initialize/lesson_content/leccion-2-Aventuras-espaciales-en-go.md
- scripts/initialize/lesson_content/leccion-2-Aventuras-y-Maravillas-de-python-.md
- scripts/initialize/lesson_content/leccion-2-Java-para-Ninos.md
- scripts/initialize/lesson_content/leccion-2-Recetas-de-TypeScript.md
Add new images to enhance visual content in lesson pages.
> feat: Update images in lesson content

- .idea/vcs.xml
- apps/backend/auth/src/main/java/com/cortex/backend/auth/config/SecurityConfig.java
- apps/backend/chat/src/main/java/com/cortex/backend/chat/api/ChatController.java
- apps/backend/chat/src/main/java/com/cortex/backend/chat/api/dto/ChatMessageRequest.java
- apps/backend/chat/src/main/java/com/cortex/backend/chat/api/dto/ChatRoomCreationDTO.java
- apps/backend/chat/src/main/java/com/cortex/backend/chat/config/WebSocketConfig.java
- apps/backend/chat/src/main/java/com/cortex/backend/chat/internal/ChatMessageMapper.java
- apps/backend/chat/src/main/java/com/cortex/backend/chat/internal/ChatMessageService.java
- apps/backend/core/src/main/java/com/cortex/backend/core/config/CorsConfig.java
- apps/backend/core/src/main/java/com/cortex/backend/core/domain/ChatMessage.java
- apps/frontend/nuxt.config.ts
- apps/frontend/package.json
- apps/frontend/src/components/ChatComponent.vue
- apps/frontend/src/components/FooterSection.vue
- apps/frontend/src/interfaces/chat-message-request.interface.ts
- apps/frontend/src/interfaces/index.ts
- apps/frontend/src/pages/chat.vue
- apps/frontend/src/plugins/websocket.ts
- bruno/Chat/Create Chat Room.bru
- bruno/Chat/See messages.bru
- bruno/environments/Cortex Dev.bru
- pnpm-lock.yaml
This pull request adds websocket client dependencies and updates the fields in the `ChatMessage` class. 
Changes:
- Added websocket client dependencies
- Updated fields in the `ChatMessage` class
These changes enhance the functionality related to handling websocket connections and managing chat messages.
> feat: Add websocket client dependencies and update ChatMessage fields

- .cargo/config.toml
- .github/workflows/desktop-release.yml
This pull request adds an LLVM installation step for macOS to improve the build process. It also updates the linker flags to enhance compatibility and performance.
> build: Add LLVM installation step for macOS and update linker flags.

- apps/backend/core/src/main/java/com/cortex/backend/core/config/CorsConfig.java
This pull request refactors the CORS configuration by updating the allowed origins to include `http://tauri.localhost`. This change ensures that requests from the specified origin are permitted, enhancing the flexibility and security of the web application.
> refactor(cors): update allowed origins to include http://tauri.localhost

- apps/desktop/src/components/UserAccount.vue
This pull request includes a refactor to improve the user sign out process and error handling. The changes made aim to enhance the overall user experience and address any potential issues related to user sign out.
> refactor: Improve user sign out process and error handling

- apps/desktop/src/pages/auth/login.vue
This pull request includes style updates to the login form container. Changes include modifying the width and alignment, as well as updating the layout for better alignment.
> ic-branch-2

- apps/desktop/src/app.vue
- apps/desktop/src/components/UserAccount.vue
- apps/desktop/src/components/update/UpdateModal.vue
- apps/desktop/src/composables/useUpdater.ts
- apps/desktop/src/pages/auth/login.vue
- apps/desktop/src/stores/user.store.ts
This pull request includes several improvements and new features to enhance the user experience in the application.
Changes:
- Updated `app.vue` to include the `UpdateModal` component for better user interaction.
- Improved error handling and logging in the user store to provide a smoother user experience.
- Enhanced the handling of auth token retrieval and set in the login page for increased security.
- Refactored the user account dropdown UI and added the ability to handle scenarios where no updates are available in the `UpdateModal`.
> clear-user-store-and-token-fix

- apps/frontend/src/components/landing/LandingHero.vue
- Updated landing hero section styles to enhance readability and visual appeal
- Adjusted button colors for better contrast and accessibility
The changes were made to improve the overall user experience on the landing page and make it more engaging for visitors. 
1. Navigate to the landing page
2. Verify the updated hero section styles
3. Check the button colors for improved contrast
4. Ensure the changes enhance the visual appeal and readability for users
<details>
<summary>Reviewer Checklist</summary>
</details>
> style: Update landing hero section styles and button colors

- apps/backend/engine/src/main/java/com/cortex/backend/engine/internal/docker/DockerExecutionService.java
- docker-compose.yml
- Fixed an issue with Docker that was causing an IOException.
- Refactored the LanguageInitializer's executeCommand method for Maven and TypeScript in the engine module.
- Added line breaks in record classes.
These changes should address the issue with the engine not executing code.
> fix-engine-not-executing-code

- apps/backend/chat/src/main/java/com/cortex/backend/chat/config/AiConfig.java
This pull request adds a memory advisor to the chat client builder for in-memory chat memory.
> feat: Add memory advisor to chat client builder for in-memory chat memory.

- apps/desktop/src/components/settings/AISettings.vue
This pull request introduces a new feature to add AI model settings in the `AISettings.vue` component. This update enhances the functionality of the application by allowing users to customize their AI model settings. The new feature is designed to improve the overall user experience and provide more control over the AI models utilized in the application.
Changes:
- Added AI model settings in `AISettings.vue`.
Please review the code changes and provide feedback.
> feat: Add AI model settings in AISettings.vue.

- apps/desktop/nuxt.config.ts
- apps/desktop/src/components/ai/ModelSelector.vue
- apps/desktop/src/components/settings/AISettings.vue
- apps/desktop/src/composables/useErrorHandler.ts
- apps/desktop/src/composables/useExercise.ts
- apps/desktop/src/composables/useKeystore.ts
- apps/desktop/src/composables/useUpdater.ts
- apps/desktop/src/pages/error.vue
- apps/desktop/src/pages/exercises/[id]/solve.vue
- apps/desktop/src/plugins/auth-sync.ts
- apps/desktop/src/plugins/error-handler.ts
- apps/desktop/src/stores/ai-provider.store.ts
- apps/desktop/src/stores/useChat.store.ts
- apps/desktop/src/stores/user.store.ts
This pull request refactors the AI settings adapter for better configuration handling and error display. 
- The `auth-sync-refactor-ai-settings-adapter` updates include:
- Refactored provider configuration handling in `ai-provider` to manage configuration status and errors more effectively.
- Added an error page with error details and a home button for better user experience in the UI. 
These changes aim to improve the authentication synchronization process related to AI settings and enhance error handling in the user interface.
> auth-sync-refactor-ai-settings-adapter

- apps/frontend/src/components/FooterSection.vue
This pull request refactors the code in FooterSection.vue by removing an unnecessary import. This helps to keep the codebase clean and organized.
> refactor: Remove unnecessary import in FooterSection.vue

- apps/frontend/src/components/AppFooter.vue
- apps/frontend/src/components/AppHeader.vue
- apps/frontend/src/components/auth/LoginForm.vue
- apps/frontend/src/components/landing/CommonQuestions.vue
- apps/frontend/src/components/landing/LandingHero.vue
- apps/frontend/src/components/landing/PricingSection.vue
- apps/frontend/src/layouts/auth/default.vue
- Update titles and prices to Spanish
- Translate features and button texts
- Update text content in landing page pricing section
- Enhance user experience with localized content
> feat: Update pricing section with translated content and button text

- apps/desktop/src/components/AppSidebar.vue
- apps/desktop/src/components/UserAccount.vue
- apps/desktop/src/components/auth/LoginForm.vue
- apps/desktop/src/components/profile/UserProgress.vue
- apps/desktop/src/components/profile/UserRoadmaps.vue
- apps/desktop/src/components/profile/UserWelcome.vue
- apps/desktop/src/layouts/auth/default.vue
- Update "My Roadmaps" to "Mis Roadmaps" in UserRoadmaps.vue
- Update "Exercises" to "Ejercicios" in UserProgress.vue
- Update labels from English to Spanish in LoginForm.vue
> refactor: Update text to Spanish in User components

- packages/shared/components/exercise/ExerciseHeader.vue
This pull request adds an AI model selector to the exercise header, enhancing the user experience by allowing users to easily select different AI models for their exercises. This feature aims to provide more customization options and flexibility to users when working on exercises.
> feat(exercise): add AI model selector to exercise header

- apps/desktop/src/components/settings/SettingsSheet.vue
- apps/desktop/src/pages/exercises/[id]/solve.vue
- packages/shared/components/exercise/ExerciseHeader.vue
Refactor the ExerciseHeader component by removing 
unnecessary code related to AI models and integrating 
a SettingsSheet component for improved settings 
management. Update v-model bindings for selected model 
and open state in the new component. This simplifies 
the model selection process and enhances user 
experience by providing a dedicated settings interface.
> feat: refactor ExerciseHeader and add settings sheet

- apps/frontend/src/components/landing/CommonQuestions.vue
- apps/frontend/src/components/landing/LandingHero.vue
Enhance the visual design of the LandingHero component by 
updating the heading size and background color. Add a new FAQ 
section in the CommonQuestions component with collapsible items 
to address common user inquiries. This improves user engagement 
and provides essential information in a clear format.
> feat: update LandingHero styles and add FAQ section

- apps/backend/engine/src/main/java/com/cortex/backend/engine/internal/parser/JavaTestResultParser.java
- apps/backend/engine/src/main/java/com/cortex/backend/engine/internal/parser/PythonTestResultParser.java
- apps/backend/engine/src/main/java/com/cortex/backend/engine/internal/parser/RustTestResultParser.java
- apps/backend/engine/src/main/java/com/cortex/backend/engine/internal/parser/TypeScriptTestResultParser.java
Add new regex patterns for test files, individual tests, and failed tests. 
Implement output validation and summary generation. Improve error handling 
for empty output and compilation failures. This enhances the parser's 
capabilities, providing clearer and more detailed results for TypeScript 
test runs.
> feat(parser): enhance TypeScript test result parsing

- packages/shared/components/CodeEditor.vue
- packages/shared/composables/editor/index.ts
- packages/shared/composables/editor/useEditorCode.ts
- packages/shared/composables/editor/useEditorCompletions.ts
- packages/shared/composables/editor/useEditorExtensions.ts
- packages/shared/composables/editor/useEditorLinting.ts
- packages/shared/composables/editor/useEditorTheme.ts
Add the `useEditorCode` composable to manage code updates and emissions in the CodeEditor component. This change centralizes code handling logic, improves reactivity, and simplifies the CodeEditor component by reducing its complexity. The new composable emits events for code updates and changes, enhancing the overall functionality and maintainability of the codebase.
> feat(editor): implement useEditorCode composable for code handling

- apps/desktop/src/error.vue
Adds a horizontal scrollbar to the stack trace view for better 
navigation of lengthy error messages. Updates CSS classes to 
ensure full-width elements are displayed consistently. These 
changes enhance the user experience and readability in the 
error log display.
> refactor(error): improve layout and add horizontal scrollbar

- apps/desktop/src-tauri/Cargo.toml
- apps/desktop/src-tauri/capabilities/default.json
- apps/desktop/src/components/TitleBar.vue
- apps/desktop/src/components/TitlebarMenu.vue
- apps/desktop/src/layouts/auth/default.vue
- apps/desktop/src/layouts/default.vue
Update titlebar component styles for better visibility. Change text 
color to white and update hover states to improve user experience. 
Replace background with a more suitable translucent color.
> style: enhance titlebar with improved color contrast

- apps/frontend/src/components/landing/PricingSection.vue
Change the plan prices from USD to CLP for better local currency  
alignment. Update button text to 'Contactanos' to improve user  
engagement. Highlight new changes to enhance visibility and  
clarity for users evaluating subscription options.
> fix: update pricing details and button text in PricingSection

- apps/frontend/src/components/auth/LoginForm.vue
- apps/frontend/src/components/auth/PasswordResetDialog.vue
- apps/frontend/src/components/landing/LandingHero.vue
Add a new PasswordResetDialog component to enhance user
experience in the authentication process. This component allows
users to reset their password by submitting their email. It
includes a simple form with validation and simulated API call
for resetting the password. Update the LoginForm to integrate
the PasswordResetDialog, removing the previous non-functional 
link to the password reset option.
> feat(auth): add password reset dialog component

- apps/frontend/src/components/auth/OAuthProfileForm.vue
- apps/frontend/src/interfaces/user.interface.ts
- apps/frontend/src/utils/form.ts
Renames profile fields in the form utility and Vue components to 
follow camelCase conventions. Updates validation logic to handle 
date parsing more robustly and adds error logging for invalid 
inputs. This enhances code consistency and improves error 
handling for better user experience.
> refactor: standardize profile field names and improve validation

- apps/backend/user/src/main/java/com/cortex/backend/user/api/dto/ChangePasswordRequest.java
Adds `@NoArgsConstructor` and `@AllArgsConstructor` annotations to the
`ChangePasswordRequest` class to generate default and all-args constructors. This simplifies the class and makes it easier to create
instances of the class.
> feat: Add lombok annotations to ChangePasswordRequest

- scripts/initialize/data.json
- scripts/initialize/lesson_content/leccion-3-aventuras-espaciales-en-go.md
- scripts/initialize/lesson_content/leccion-3-los-guardianes-del-codigo-rust.md
- scripts/initialize/lesson_content/leccion-3-mas-alla-de-la-magia-de-python.md
- scripts/initialize/lesson_content/leccion-3-typescript-en-accion-proyectos-practicos.md
- scripts/initialize/lesson_content/leccion-3-¡aventuras-con-arrays-y-juegos-con-java.md
- scripts/initialize/lesson_content/leccion-4-aventuras-con-bibliotecas-magicas-en-python.md
- scripts/initialize/lesson_content/leccion-4-explorando-nuevos-horizontes-en-go.md
- scripts/initialize/lesson_content/leccion-4-los-defensores-del-reino-rust.md
- scripts/initialize/lesson_content/leccion-4-typescript-orientado-a-objetos.md
- scripts/initialize/lesson_content/leccion-4-¡superheroes-y-metodos-de-java.md
- scripts/initialize/lesson_content/leccion-5-creando-nuestros-propios-modulos-magicos-con-python.md
- scripts/initialize/lesson_content/leccion-5-decoradores-typescript-sazona-tus-aplicaciones.md
- scripts/initialize/lesson_content/leccion-5-la-gran-biblioteca-de-los-magos-rust.md
- scripts/initialize/lesson_content/leccion-5-nuevas-dimensiones-en-go.md
- scripts/initialize/lesson_content/leccion-5-¡el-parque-de-diversiones-virtual-el-potencial-de-java.md
Update course names, descriptions, and tags in data.json to
introduce new educational offerings. Set the is_published status 
to true for all updated entries to make them available for users. 
This enhances the diversity of learning paths and aligns with 
current industry trends.
> feat(data): update courses to reflect new content and tags

- scripts/initialize/data.json
- scripts/initialize/lesson_content/leccion_1_tu_primera_ventana_magica_introduccion_a_jframe
This commit introduces the first steps in creating a GUI application using Java Swing. The changes include:
- Explaining what Java Swing is and its historical context
- Highlighting the advantages and challenges of learning Swing in the modern era
- Providing a step-by-step walkthrough of creating a simple Swing application with a window, label, and button
- Describing the overall structure of a Swing application and its key components
The goal of these changes is to onboard the reader into the world of Swing GUI programming and set the foundation for more advanced Swing concepts to come.
> feat: Create a magical first window with Java Swing

- Cargo.toml
- apps/desktop/nuxt.config.ts
- apps/desktop/package.json
- apps/desktop/src-tauri/Cargo.toml
- apps/desktop/src-tauri/crates/common/Cargo.toml
- apps/desktop/src-tauri/crates/common/src/lib.rs
- apps/desktop/src-tauri/crates/education/src/courses/commands/mod.rs
- apps/desktop/src-tauri/crates/education/src/courses/mod.rs
- apps/desktop/src-tauri/crates/education/src/lessons/commands/mod.rs
- apps/desktop/src-tauri/crates/education/src/lessons/mod.rs
- apps/desktop/src-tauri/crates/education/src/lib.rs
- apps/desktop/src-tauri/crates/education/src/modules/commands/mod.rs
- apps/desktop/src-tauri/crates/education/src/modules/mod.rs
- apps/desktop/src-tauri/crates/education/src/roadmaps/commands/mod.rs
- apps/desktop/src-tauri/crates/education/src/roadmaps/mod.rs
- apps/desktop/src-tauri/crates/error/src/lib.rs
- apps/desktop/src-tauri/src/lib.rs
- apps/desktop/src/components/TipTapButton.vue
- apps/desktop/src/components/TiptapEditor.vue
- apps/desktop/src/components/roadmap/RoadmapForm.vue
- apps/desktop/src/pages/index.vue
- apps/desktop/src/pages/roadmaps/create.vue
- apps/frontend/nuxt.config.ts
- apps/frontend/package.json
- packages/shared/types/education.interface.ts
- pnpm-lock.yaml
This pull request adds new course management functionality to the application. The key changes include:
- Added new dependencies for generating confetti animations and improved state management with Pinia in Nuxt.js.
- Implemented the ability to create a new course roadmap, allowing users to plan and organize their course content.
These changes will enhance the overall user experience and provide more robust course management capabilities for the application.
> add-course-management-functionality

- apps/desktop/src/components/roadmap/RoadmapForm.vue
The changes made in this commit focus on improving the user interface and functionality of the Roadmap Form component. The key changes are:
1. Reorganized the form layout to have a more visually appealing and intuitive structure.
2. Added a hero image section that allows users to upload and preview a cover image for the roadmap.
3. Implemented a Notion-style title input field for a cleaner and more modern look.
4. Improved the tags input section, making it more user-friendly and visually consistent.
5. Streamlined the courses selection section, providing a better user experience.
6. Enhanced the description editor, making it more prominent and easier to use.
These changes aim to improve the overall user experience and make the Roadmap Form more visually appealing and intuitive to use.
> feat(roadmap): Enhance Roadmap Form UI and functionality

- apps/desktop/src/pages/splashscreen.vue
The changes made to the `splashscreen.vue` file include:
1. Importing additional dependencies, such as `open` from `@tauri-apps/plugin-shell`, `debug` and `error` from `@tauri-apps/plugin-log`, and various icons and images.
2. Defining a `splashImages` array and a `currentImage` ref to randomly display one of the splash images.
3. Modifying the `initApp` function to include a timeout for debugging purposes and handling errors more gracefully.
4. Redesigning the splashscreen layout to have a left column with the Cortex logo, loading text, and social media links, and a right column with a responsive illustration.
5. Removing the progress bar and status message from the previous implementation.
These changes aim to enhance the visual appeal and user experience of the Cortex desktop …
> feat(splashscreen): Enhance the splashscreen design and functionality

- docker/typescript.Dockerfile
- scripts/pull_docker_images.py
- Update the TypeScript Dockerfile to use the latest dependencies from the
cortex-exercises repository
- Implement a check and update mechanism for the cortex-exercises repository
to ensure the latest changes are used when building the custom TypeScript
Docker image
- Improve the build process by showing the output in real-time and adding
the `--no-cache` and `--progress` flags to the `docker build` command
> feat(docker): update TypeScript Dockerfile and image build

- apps/frontend/src/components/Profile/EditProfileModal.vue
- apps/frontend/src/components/Profile/UserProfile.vue
- apps/frontend/src/components/UserMenu.vue
- apps/frontend/src/components/userCreation/course.vue
- apps/frontend/src/components/userCreation/roadmap.vue
- apps/frontend/src/components/usersetting/setting.vue
- apps/frontend/src/pages/config.vue
- apps/frontend/src/pages/courses.vue
- apps/frontend/src/pages/profile.vue
- apps/frontend/src/pages/roadmaps.vue
This pull request introduces new functionality for user profile management, enhancing the overall user experience. 
**Changes Made:**
- Added the ability for users to edit their profiles via the `EditProfileModal` component.
- Users can now update their avatar, first name, last name, username, email, date of birth, country code, and gender directly from the profile page.
These improvements enable smoother interaction with the profile features and provide users with more control over their personal information.
> feat(profile): add profile functions 

- apps/desktop/src/pages/explore/index.vue
- apps/frontend/src/composables/useRoadmaps.ts
- apps/frontend/src/pages/explore/[slug]/index.vue
- apps/frontend/src/pages/explore/index.vue
- apps/frontend/src/pages/my-roadmaps/[slug]/index.vue
- apps/frontend/src/pages/my-roadmaps/index.vue
- packages/shared/components/roadmaps/RoadmapList.vue
Este pull request introduce mejoras significativas en la lógica de obtención de la hoja de ruta y el manejo errores. Se ha refactorizado la lógica de obtención incluir un parámetroisAdmin`, lo que permite un mejor control de acceso. Además, se ha actualizado el manejo de errores para utilizar un manejador de errores centralizado, mejorando así la consistencia y mantenibilidad del código.
También se han realizado ajustes en el componente RoadmapList para garantizar la seguridad de tipos con TypeScript. Por último, se ha mejorado la gestión del estado de carga en la interfaz de usuario, lo que contribuye a una mejor experiencia para el usuario. 
Estos cambios son parte de un esfuerzo continuo por optimizar la aplicación y asegurar que el código sea más robusto y fácil de mantener.
> ✨ feat: enhance roadmap fetching and error handling

- apps/desktop/src/components/profile/UserEdit.vue
- apps/desktop/src/components/profile/UserRoadmaps.vue
Create a new UserEdit component to allow users to edit their profile data.
The component utilizes Vue's composition API, handles avatar changes, and 
provides a form for editing personal details. This enhances user experience 
by enabling profile updates directly within the application.
> feat: add user profile editing component

- apps/desktop/src-tauri/crates/ai_chat/src/commands/mod.rs
- apps/desktop/src-tauri/crates/ai_chat/src/keystore/manager.rs
- apps/desktop/src-tauri/crates/ai_chat/src/keystore/mod.rs
- apps/desktop/src-tauri/crates/ai_chat/src/providers/gemini.rs
- apps/desktop/src-tauri/crates/ai_chat/src/providers/mod.rs
- apps/desktop/src-tauri/crates/ai_chat/src/session/manager.rs
- apps/desktop/src/components/ai/ModelSelector.vue
- apps/desktop/src/components/settings/AISettings.vue
- apps/desktop/src/composables/useKeystore.ts
- apps/desktop/src/stores/ai-provider.store.ts
- bruno/Gemini.bru
- bruno/environments/Cortex Docker.bru
This pull request introduces two major integrations:
1. **Add support for the Gemini model**: The application now supports the Gemini AI model provided by Google Cloud. This includes implementing the necessary data structures, the `GeminiProvider` struct, and methods to set the API key and send requests to the Gemini API. A detailed system prompt has been constructed to guide the Gemini model in providing helpful and formatted responses to the user.
2. **Add support for storing multiple provider API keys**: The `KeyStore` struct has been refactored to use a `HashMap` to store provider names and their corresponding API keys. This allows for more flexibility in managing multiple provider keys. The `KeystoreManager` methods have been updated to work with the new `KeyStore` structure, …
> add-gemini-model

- apps/desktop/src-tauri/crates/ai_chat/src/providers/gemini.rs
- apps/desktop/src-tauri/crates/ai_chat/src/session/mod.rs
- apps/desktop/src/composables/useAIChat.ts
- apps/desktop/src/composables/useKeystore.ts
This pull request introduces a new feature to handle the streaming response from the Gemini API in the AI chat application. The key changes are:
1. Refactors the `build_prompt` method to separate the prompt construction logic and make it more readable.
2. Implements the `process_stream` method to handle the streaming response from the Gemini API. This method extracts the JSON objects from the response stream, processes the content, and emits events to the application window.
3. Adds a helper method `extract_json_object` to extract the next JSON object from the response buffer.
These changes improve the overall handling of the Gemini API response, making the code more robust and maintainable. Handling the streaming response from the Gemini API is a complex task, as each stream comes in a …
> handle-stream-in-gemini

- apps/frontend/src/components/UserMenu.vue
- apps/frontend/src/components/userCreation/roadmap.vue
Changes the "my-roadmaps" route to "roadmaps" in the UserMenu 
component for consistency. Simplifies the roadmap.vue file by 
removing unnecessary code and enhancing the user interface 
with a more informative header and a call to action for 
exploring roadmaps, improving user experience and clarity.
> refactor: update roadmap links and enhance user menu

- scripts/initialize/lesson_content/leccion-4-explorando-nuevos-horizontes-en-go.md
- scripts/initialize/lesson_content/leccion-5-nuevas-dimensiones-en-go.md
Remove unnecessary blank lines and format code blocks 
for better readability in "leccion-4" and "leccion-5". 
These changes enhance the overall clarity and presentation 
of the educational material, ensuring better learning 
experience for students.
> fix: clean up code blocks in lesson content

- scripts/initialize/lesson_content/leccion-1-Los-super-heroes-rust.md
- scripts/initialize/lesson_content/leccion-3-mas-alla-de-la-magia-de-python.md
- scripts/initialize/lesson_content/leccion-4-aventuras-con-bibliotecas-magicas-en-python.md
- scripts/initialize/lesson_content/leccion-5-la-gran-biblioteca-de-los-magos-rust.md
- scripts/initialize/lesson_content/leccion-5-modulos-magicos-con-python.md
- scripts/initialize/lesson_content/leccion-5-nuevas-dimensiones-en-go.md
Correct image links and adjust lesson section numbering 
for consistency across markdown files. Enhance clarity of 
exercises and conclusions to improve the learning experience.
> fix: update image links and lesson formatting

- apps/desktop/src/components/crud/roadmap/AssignCourseToRoadmap.vue
- apps/desktop/src/composables/useCourseAssignment.ts
- scripts/initialize/lesson_content/leccion-5-nuevas-dimensiones-en-go.md
Este pull request introduce mejoras significativas en la interfaz de usuario y la funcionalidad de la asignación de cursos. A continuación se detallan los cambios realizados:
- Se han añadido estilos de selección de usuario para prevenir la selección de texto en las tarjetas.
- Se han actualizado las clases de las tarjetas para los cursos asignados y disponibles, mejorando así la consistencia de la interfaz de usuario.
- Se ha modificado la lógica de orden de visualización para que comience desde 1 en lugar de 0, lo que proporciona una mejor experiencia al usuario.
- Se ha habilitado la opción `forceFallback` en la asign de cursos para mejorar el comportamiento de arrastrar y soltar.
Se ha actualizado el enlace de la imagen en el contenido de la lección para garantizar su precisión.
Estos …
> ✨ feat: enhance course assignment UI and functionality

- apps/frontend/src/components/Profile/EditProfileModal.vue
- apps/frontend/src/components/Profile/UserProfile.vue
Add file type and size validation for avatar upload in 
EditProfileModal. Update profile handling logic to include 
user feedback on actions. Implement account deletion 
functionality with proper loading states and error handling.  
Refactor template structure for improved readability.
> feat: enhance profile management and validation logic

- apps/desktop/src/components/crud/roadmap/AssignCourseToRoadmap.vue
- apps/desktop/src/composables/useLessons.ts
- apps/desktop/src/composables/useModules.ts
- apps/desktop/src/composables/useRoadmaps.ts
- apps/desktop/src/pages/modules/[slugModule]/lessons/[slugLesson].vue
- apps/desktop/src/pages/my-roadmaps/[slug]/courses/[slugCourse].vue
- apps/desktop/src/pages/my-roadmaps/[slug]/index.vue
- apps/desktop/src/pages/my-roadmaps/index.vue
- packages/shared/components/roadmaps/CoursesCard.vue
Este pull request introduce la funcionalidad de gestión de hojas de ruta en la página "Mis Hojas de Ruta", que incluye características de ordenamiento y paginación. Se ha añadido un nuevo composable para la obtención de lecciones, mejorando así la experiencia del usuario al permitir que los administradores visualicen todas las hojas de ruta. Además, se han implementado estados de carga utilizando componentes esqueleto para una mejor interacción visual.
- Implementación de la gestión de hojas de ruta.
- Funcionalidades de ordenamiento y paginación.
- Nuevo composable para la obtención de lecciones.
- Mejora en la experiencia del usuario para administradores.
- Inclusión de estados de carga con componentes esqueleto. 
Este avance busca optimizar la navegación y la administración de cursos, …
> ✨ feat: implement roadmap management and sorting features

- apps/frontend/src/components/PricingCard.vue
- apps/frontend/src/components/landing/PricingSection.vue
- apps/frontend/src/pages/exercises/[id]/index.vue
- apps/frontend/src/pages/exercises/[id]/solve.vue
- apps/frontend/src/pages/exercises/index.vue
- apps/frontend/src/pages/index.vue
- apps/frontend/src/pages/modules/[slugModule]/lessons/[slugLesson].vue
- apps/frontend/src/pages/plans/index.vue
- packages/shared/components/ui/carousel/CarouselNext.vue
- packages/shared/components/ui/carousel/CarouselPrevious.vue
- packages/shared/types/education.interface.ts
Este Pull Request introduce un nuevo componente de hoja de ejercicios en la página de lecciones, mejorando así la interacción del usuario. Además, se actualizan los componentes `PricingCard` y `PricingSection` para incluir nuevas propiedades relacionadas con la ruta y el estado de habilitación. Se implementan mejoras en la navegación y el diseño en la página de planes, integrando la sección de precios con la ruta completa. Estas modificaciones buscan mejorar la experiencia del usuario y mantener una navegación consistente a lo largo de la aplicación.
> ✨ feat: add exercise sheet and update pricing components

- .idea/vcs.xml
- apps/desktop/src-tauri/crates/education/src/lib.rs
The changes add a new `ExerciseInfo` struct to the `Lesson` struct, which includes
information about the exercises associated with each lesson, such as the exercise
ID, slug, title, completion status, and points. This allows for more detailed
tracking and display of lesson exercises.
> feat(education): Add exercise information to lessons

- apps/desktop/src/components/LoadingOverlay.vue
Updates the loading messages in LoadingOverlay.vue to Spanish. This change 
enhances accessibility and provides a better user experience for Spanish 
speakers. The listed humorous messages are now localized, maintaining the 
original intent while catering to a wider audience.
> feat(i18n): translate loading messages to Spanish

- Cargo.toml
- apps/desktop/src-tauri/Cargo.toml
Here is the pull request description:
This pull request updates the project dependencies to their latest versions. The changes include:
- Updating all dependencies to their latest compatible versions to ensure the project is using the most up-to-date and secure packages.
This change will help keep the project secure and take advantage of the latest features and bug fixes provided by the dependency maintainers.
> feat(deps): update dependencies to latest versions

- apps/desktop/package.json
- apps/desktop/src/components/ai/chat.vue
This commit introduces the following changes to the `chat.vue` component:
1. Integrates the `@f3ve/vue-markdown-it` library to handle Markdown rendering with improved syntax highlighting.
2. Registers support for various programming language syntax highlighting using the `highlight.js` library.
3. Applies custom styles for the Markdown-rendered content, including syntax highlighting and dark mode support.
4. Removes the previous `parseMarkdown` function and related logic, as the new `VueMarkdownIt` component handles the Markdown rendering.
5. Updates the `package.json` file to include the `highlight.js` dependency.
These changes aim to enhance the user experience by providing better code syntax highlighting and a more polished Markdown rendering in the chat component.
> feat(chat): Implement code syntax highlighting and improve Markdown rendering

- apps/desktop/src-tauri/src/lib.rs
- apps/desktop/src/components/ai/chat.vue
- apps/desktop/src/pages/modules/[slugModule]/lessons/[slugLesson].vue
- apps/desktop/src/plugins/markdown.ts
This commit includes the following changes:
1. Improve the markdown rendering in the AI chat component by using the global `$markdown.options` instead of a local `markdownOptions` object.
2. Add more specific log level filters for `zbus` and related modules in the Tauri application setup. This helps to reduce the noise in the logs for production builds.
3. Refactor the log level configuration for the `cortex_lib` module to use a more concise syntax.
These changes aim to enhance the overall user experience and improve the maintainability of the application by optimizing the markdown rendering and the logging system.
> feat(desktop): improve markdown rendering and logging

- apps/frontend/src/components/landing/PricingSection.vue
Add a new annual pricing plan to the PricingSection component. This 
includes setting the title, price, billing period, and specific features 
that enhance value for users. The change aims to provide users with more 
flexible subscription options and promote long-term engagement.
> feat(pricing): add annual plan with features and details

- apps/frontend/src/components/AppHeader.vue
- apps/frontend/src/components/Profile/AvatarUpload.vue
- apps/frontend/src/components/Profile/UserProfile.vue
Este pull request introduce mejoras significativas en los componentes de perfil de usuario y navegación. Se ha realizado un refactor en `UserProfile.vue` para optimizar la visualización del correo electrónico con un estilo responsivo. Además, se ha actualizado `AvatarUpload.vue` para garantizar un tamaño de avatar consistente. Por último, se ha mejorado `AppHeader.vue` añadiendo funcionalidad de alternancia de menú y mejorando el diseño para ofrecer una mejor experiencia de navegación en escritorio. Estos cambios tienen como objetivo mejorar la experiencia del usuario y la consistencia de la interfaz.
> ✨ feat: enhance user profile and navigation components

- apps/frontend/src/components/AppFooter.vue
- apps/frontend/src/components/CompanyInfo.vue
- apps/frontend/src/components/FooterSection.vue
- apps/frontend/src/pages/terms-and-conditions.vue
1. **Add footer content and structure**: This commit adds new content and structure to the footer component in the frontend application. The main changes are:
- Adds three new data objects (`companyItems`, `productItems`, `legalItems`) to store the footer links and their corresponding text and URLs.
- Updates the `FooterSection` component to accept an array of objects with `text` and `link` properties, instead of just an array of strings.
- Replaces the hardcoded footer links with the new data objects in the `AppFooter` component.
- Updates the `CompanyInfo` component to display the correct company address.
These changes improve the maintainability and flexibility of the footer by separating the content from the structure, making it easier to update the footer links in the future.
2. …
> chore: add terms and conditions

- apps/backend/auth/src/main/java/com/cortex/backend/auth/internal/AuthenticationServiceImpl.java
Adds email validation for user registration. Previously, the account
was automatically activated in dev mode, but now the validation email
is always sent, regardless of the environment.
This change ensures that all user accounts go through the same
validation process, improving the security and consistency of the
authentication system.
> ✨ feat(auth): Implement email validation for user registration

- apps/desktop/src/components/UserAccount.vue
- apps/desktop/src/components/ai/chat.vue
- apps/desktop/src/layouts/default.vue
- apps/desktop/src/pages/exercises/[id]/solve.vue
- apps/desktop/src/pages/modules/[slugModule]/lessons/[slugLesson].vue
- apps/frontend/src/pages/exercises/[id]/solve.vue
- packages/shared/components/CodeEditor.vue
- packages/shared/components/exercise/ExecutionResults.vue
- packages/shared/components/exercise/ExerciseHeader.vue
- packages/shared/components/exercise/ExercisePanel.vue
- packages/shared/components/exercise/HintsTab.vue
- packages/shared/themes/material-dark.ts
- packages/shared/themes/material-light.ts
Este pull request se centra en la refactorización componente `ExercisePanel` y otros componentes relacionados para mejorar el diseño y los estilos. Se ha reemplazado el uso de `ScrollArea` por elementos `div`, lo que proporciona una mayor flexibilidad en el diseño. Además, se han actualizado los colores de fondo en los temas para lograr un mejor contraste visual. También se han añadido nuevos estilos para bordes redondeados y sugerencias de error en los componentes de chat, con el objetivo de mejorar la experiencia del usuario. 
Los cambios realizados son los siguientes:
- Simplificación del diseño de los componentes.
- Mejora de los estilos visuales.
- Implementación de bordes redondeados y mensajes de error más claros en los componentes de chat. 
Estos ajustes buscan optimizar la …
> ✨ refactor: simplify layout and improve styles in components

- apps/frontend/src/components/userCreation/roadmap.vue
Refactor the userCreation roadmap component to enhance the user 
experience. The changes include an updated structure with a 
new design, improved headings, and descriptive text to 
better communicate the purpose of the platform. The layout 
is now more visually appealing and accessible, promoting 
greater engagement with the content.
> feat: update userCreation roadmap component layout

- apps/frontend/src/components/Profile/UserProfile.vue
- apps/frontend/src/pages/plans/index.vue
Adds a new section in the UserProfile component for activating a 
premium subscription. This includes a title, description, and input 
for an activation code, enhancing user engagement and access to 
exclusive content. Also sets the layout to false in the plans page 
to improve the overall user experience.
> ✨ feat: add subscription activation feature to UserProfile

- apps/frontend/src/components/LemonSqueezyButton.vue
- apps/frontend/src/components/Profile/UserProfile.vue
- apps/frontend/src/components/userCreation/roadmap.vue
- apps/frontend/src/pages/about.vue
Este pull request introduce mejoras significativas en las secciones de perfil de usuario y testimonios. Se ha refactorizado el componente UserProfile para incluir un efecto de confeti al activar la suscripción, lo que mejora la experiencia del usuario. Además, se ha ajustado el diseño para lograr una mejor alineación y usabilidad.
Se ha añadido un nuevo testimonio de "Don Quirogas" para enriquecer el contenido de la página "Acerca de". También se han actualizado los estilos de los botones para asegurar consistencia y mejorar el atractivo visual en todos los componentes.
Estos cambios están destinados a ofrecer una experiencia más atractiva y coherente para los usuarios.
> ✨ feat: enhance user profile and testimonials sections

- apps/frontend/nuxt.config.ts
- apps/frontend/src/components/auth/RegisterForm.vue
- apps/frontend/src/pages/auth/register.vue
Refactor field names in the registration form to use snake_case for 
consistency across the application. Update the `countryCode`, 
`dateOfBirth`, and related fields to `
> ✨ feat(auth): update field names for consistency and clarity

- apps/frontend/src/components/auth/RegisterForm.vue
- apps/frontend/src/schemas/register.schema.ts
This pull request introduces a ref of the field names the registration form and schema, transitioning from snake_case to camelCase. This change enhances the consistency of the codebase and aligns it with JavaScript conventions, making it more intuitive for developers. 
Additionally, scoped styles have been applied to improve the visual appearance of the registration form, ensuring a better user experience. 
Key changes include:
- Updated field names to camelCase for better readability and consistency.
- Enhanced styling for the registration form to improve its overall look and feel.
These updates aim to streamline the code and provide a more cohesive development experience.
> ✨ refactor: update field names for consistency and clarity

- apps/frontend/src/components/auth/LoginForm.vue
- apps/frontend/src/components/auth/RegisterForm.vue
Update the layout and styling of the RegisterForm component to enhance 
the user interface. Adjust the card and header styles for better 
alignment and spacing. Improve button styles and add separators for 
visual clarity. These changes aim to create a more cohesive and 
user-friendly registration experience.
> ✨ style: Refactor RegisterForm layout and improve design

- apps/desktop/src/pages/modules/[slugModule]/lessons/[slugLesson].vue
- apps/frontend/src/components/auth/RegisterForm.vue
- apps/frontend/src/components/landing/LandingHero.vue
- apps/frontend/src/pages/modules/[slugModule]/lessons/[slugLesson].vue
- apps/frontend/src/pages/my-roadmaps/[slug]/courses/[slugCourse].vue
- apps/frontend/src/stores/auth.store.ts
Este pull request introduce mejoras significativas en la interfaz de usuario y la navegación de la aplicación. A continuación se detallan los cambios realizados:
- Se han añadido componentes NuLink en el `theHero` para facilitar la navegación hacia las secciones "Empieza aquí" y "Explorar Roadmaps".
- Se ha mejorado el formulario de registro (`RegisterForm`) actualizando los estilos de `FormControl` para una mejor experiencia de usuario.
- Se ha implementado un mensaje informativo para las lecciones que no contienen ejercicios, tanto en la vista de frontend como en la vista de escritorio.
- Se ha actualizado la fuente de imagen a una URL de marcador de posición para mantener la consistencia visual en la aplicación.
- Se ha ajustado el endpoint de la API para la activación de cuentas, …
> ✨ feat: add navigation links and improve UI elements

- apps/desktop/src/components/AppSidebar.vue
- apps/desktop/src/composables/useNavigation.ts
- apps/desktop/src/pages/splashscreen.vue
Corrects the Spanish in the splash screen and navigation items 
to improve language accuracy. Changes include updating phrases 
to reflect proper grammar and terminology, enhancing user 
experience for Spanish-speaking users.
> fix: update Spanish translations in UI components

- apps/desktop/src-tauri/crates/education/src/courses/commands/mod.rs
- apps/desktop/src-tauri/crates/education/src/courses/mod.rs
- apps/desktop/src-tauri/crates/education/src/modules/commands/mod.rs
- apps/desktop/src-tauri/crates/education/src/modules/mod.rs
- apps/desktop/src-tauri/src/lib.rs
- apps/desktop/src/components/crud/roadmap/AssignCourseToRoadmap.vue
- apps/desktop/src/components/education/ContentTitle.vue
- apps/desktop/src/components/modules/ModuleActionsMenu.vue
- apps/desktop/src/components/roadmap/RoadmapForm.vue
- apps/desktop/src/composables/useEducationalForm.ts
- apps/desktop/src/composables/useModules.ts
- apps/desktop/src/pages/admin/courses/[id]/modules.vue
- apps/desktop/src/pages/admin/modules/[slug].vue
- apps/desktop/src/pages/admin/modules/create.vue
- apps/desktop/src/pages/admin/modules/edit.vue
- apps/desktop/src/pages/admin/modules/index.vue
- apps/desktop/src/pages/admin/roadmaps/[id]/courses.vue
- apps/desktop/src/pages/splashscreen.vue
- apps/frontend/src/composables/useLessons.ts
- apps/frontend/src/composables/useModules.ts
- apps/frontend/src/composables/useProfileCompletion.ts
- apps/frontend/src/plugins/error.ts
- bruno/Education/Course/Get Course Modules.bru
- packages/shared/components/ui/toast/index.ts
- packages/shared/composables/desktop/useDesktopErrorHandler.ts
- packages/shared/composables/front/useWebErrorHandler.ts
- packages/shared/types/education.interface.ts
Este Pull Request introduce varias mejoras y nuevas funcionalidades relacionadas con la gestión de módulos en el sistema educativo. A continuación se detallan los cambios realizados:
- Se ha añadido una nueva función para **obtener un módulo por su ID**, lo que facilita la recuperación de información específica de los módulos.
- Se ha actualizado el **CourseActionsMenu** para utilizar `courseSlug` en lugar de `courseId`, mejorando así la claridad y la legibilidad del código.
- Se ha modificado el **esqu del formulario educativo** para permitir condicionalmente etiquetas basadas en el tipo de contenido, lo que proporciona una mayor flexibilidad en la gestión de los datos.
- Se han ajustado los **manejadores de errores** en la interfaz de escritorio para ofrecer una mejor claridad en la …
> ✨ feat: add fetch module by ID and update course actions

- apps/backend/auth/src/main/java/com/cortex/backend/auth/internal/AuthenticationServiceImpl.java
- package.json
- scripts/pull_docker_images.py
Este pull request incluye mejoras significativas en la estructura del proyecto y en la lógica de validación de correos electrónicos. 
- Se ha actualizado el directorio de trabajo en el script de construcción de la imagen Docker, cambiando de 'capstone' a 'cortex' para reflejar correctamente la estructura del proyecto. También se ha actualizado la ruta del Dockerfile en consecuencia.
- La lógica de validación de correos electrónicos en `AuthenticationServiceImpl` ha sido reorganizada para mejorar su legibilidad y mantenibilidad.
- Además, se ha cambiado el comando de ejecución para los scripts de Docker, utilizando 'uv run' para optimizar el rendimiento.
Estos cambios buscan no solo corregir referencias de directorio, sino también mejorar la calidad del código y la eficiencia en la …
> fix: update directory references and improve scripts
