apps/desktop/src-tauri/src/lib.rs
Update the logging configuration to set the log level of 
"cortex_lib" dynamically based on the build type. In debug 
builds, it uses `Trace` level for detailed logs, while 
in release builds, it switches to `Info` level for 
conciseness. This improves log management and 
visibility while debugging and enhances performance 
in production environments.
=> feat(logging): adjust cortex_lib log level based on config

apps/frontend/nuxt.config.ts, apps/frontend/src/components/auth/OAuthProfileForm.vue, apps/frontend/src/composables/useProfileCompletion.ts, apps/frontend/src/composables/useWebErrorHandler.ts, apps/frontend/src/interfaces/user.interface.ts, apps/frontend/src/pages/auth/callback.vue, apps/frontend/src/pages/auth/complete-profile.vue, apps/frontend/src/plugins/error.ts, apps/frontend/src/stores/auth.store.ts
Add a new error handling plugin to manage application errors globally. 
Enhance the account activation process by validating the token and improving error handling for better user feedback. Include necessary imports and update the configuration to include the new error plugin.
=> feat: add global error handling and account activation checks

bruno/Education/Roadmap/Get Roadmap By Slug.bru
Changes the API URL for retrieving the roadmap to use the new slug 
that corresponds to the "Introducción al mundo de la programación" 
course, ensuring the endpoint reflects the correct educational 
content for users.
=> feat(api): update roadmap slug for programming intro

Cargo.toml, apps/desktop/package.json, pnpm-lock.yaml
Updates the dependency for `@fabianlars/tauri-plugin-oauth` from a specific 
GitHub tarball link to version 2.0.0 across multiple files, ensuring consistency in package resolution. This change improves maintainability 
by using a versioned release instead of a direct link to the repository.
=> chore: upgrade tauri-plugin-oauth to version 2.0.0

apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapController.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapRepository.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapService.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/dto/RoadmapExerciseDTO.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapMapper.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapServiceImpl.java, apps/desktop/src-tauri/crates/education/src/lib.rs, bruno/Education/Lesson/Get Lesson By Slug.bru, bruno/Education/Modules/Get Module By Slug.bru, bruno/Exercise/Details.bru, packages/shared/types/education.interface.ts
The changes in this commit add the user ID as a parameter to the `getRoadmapBySlug` method in the `RoadmapService`. This allows the service to retrieve the roadmap details with the user's progress information, such as which exercises have been completed. This feature is necessary to provide a personalized view of the roadmap for each user.
=> feat(roadmap): Add user context to getRoadmapBySlug

apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/tauri.conf.json
Increase the version number in the Cargo.toml and tauri.conf.json files from 0.1.3 to 0.1.4. This change is necessary to reflect the latest version of the Cortex Desktop Application for Premium Users.
=> feat: Bump version to 0.1.4

.github/workflows/desktop-release.yml
The changes in this commit add the generated changelog to the release notes for the Cortex desktop application. This provides users with a detailed overview of the changes included in the new release.
The key changes are:
1. Added a new job `create-changelog` that generates the changelog using the `TriPSs/conventional-changelog-action` and stores the output in the job's outputs.
2. Updated the `build-tauri` job to wait for the `create-changelog` job to complete before proceeding.
3. Modified the `release-body` field in the `tauri-apps/tauri-action` step to include the changelog output from the `create-changelog` job.
These changes ensure that the release notes for the Cortex desktop application include a comprehensive changelog, making it easier for users to understand the updates and …
=> feat(desktop-release): add changelog to release notes

apps/desktop/src/components/update/UpdateDetails.vue
The changes in this commit address an issue where the version date was not being displayed correctly when it was missing or in an invalid format. The `formattedDate` computed property has been updated to handle these cases more gracefully, returning an empty string instead of a default message.
This ensures a better user experience by not displaying any date information when it is not available, rather than showing a generic "Fecha no disponible" message.
=> feat(update): handle missing version date gracefully

.github/workflows/desktop-release.yml
Modify the desktop release workflow to generate the changelog in the correct directory and use a custom tag prefix. This ensures the
changelog is generated for the desktop app specifically and uses a consistent tag naming convention.
=> feat(desktop-release): Improve changelog generation workflow

apps/backend/core/src/main/java/com/cortex/backend/core/domain/Course.java, apps/backend/core/src/main/java/com/cortex/backend/core/domain/Exercise.java, apps/backend/core/src/main/java/com/cortex/backend/core/domain/Lesson.java, apps/backend/core/src/main/java/com/cortex/backend/core/domain/ModuleEntity.java, apps/backend/education/src/main/java/com/cortex/backend/education/course/api/dto/CourseRequest.java, apps/backend/education/src/main/java/com/cortex/backend/education/course/api/dto/CourseResponse.java, apps/backend/education/src/main/java/com/cortex/backend/education/course/api/dto/CourseUpdateRequest.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/dto/LessonRequest.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/dto/LessonResponse.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/dto/LessonUpdateRequest.java, apps/backend/education/src/main/java/com/cortex/backend/education/module/api/dto/ModuleRequest.java, apps/backend/education/src/main/java/com/cortex/backend/education/module/api/dto/ModuleResponse.java, apps/backend/education/src/main/java/com/cortex/backend/education/module/api/dto/ModuleUpdateRequest.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/dto/RoadmapExerciseDTO.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/dto/RoadmapLessonDTO.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/dto/RoadmapModuleDTO.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapMapper.java, apps/backend/engine/src/main/java/com/cortex/backend/engine/api/dto/CreateExercise.java, apps/backend/engine/src/main/java/com/cortex/backend/engine/api/dto/ExerciseDetailsResponse.java, apps/backend/engine/src/main/java/com/cortex/backend/engine/api/dto/ExerciseResponse.java, apps/backend/engine/src/main/java/com/cortex/backend/engine/api/dto/UpdateExercise.java, apps/backend/engine/src/main/java/com/cortex/backend/engine/internal/ExerciseConfig.java, apps/desktop/src/composables/useDesktopErrorHandler.ts
This pull request introduces the following changes:
1. **Improve error handling and logging**:
- Import the `error` function from the `@tauri-apps/plugin-log` module to log errors more effectively.
- Update the `showSystemNotification` function to display a more user-friendly error message, including the error status code.
- Replace the `throw` statement with a call to the `error` function to log the fatal error details, including the error message and stack trace.
- Remove the commented-out `throw` statement, as the error is now being logged instead of thrown.
2. **Add display order to modules, lessons, and exercises**:
- Add a new `display_order` field to the `ModuleResponse`, `CourseUpdateRequest`, `Exercise`, `RoadmapExerciseDTO`, `LessonResponse`, `RoadmapLessonDTO`, `ModuleRequest`, …
=> feat: Add display order to entities

apps/backend/education/src/main/java/com/cortex/backend/education/course/internal/CourseMapper.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/dto/LessonRequest.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/internal/LessonMapper.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/internal/LessonServiceImpl.java, apps/backend/education/src/main/java/com/cortex/backend/education/module/api/dto/ModuleRequest.java, apps/backend/education/src/main/java/com/cortex/backend/education/module/internal/ModuleMapper.java, apps/backend/education/src/main/java/com/cortex/backend/education/module/internal/ModuleServiceImpl.java
The changes in this commit focus on the following improvements:
1. Added a `@Positive` validation constraint to the `displayOrder` field in the `LessonRequest` and `ModuleRequest` classes to ensure that the display order is a positive number.
2. Implemented mapping for the `displayOrder` field in the `CourseMapper` and `ModuleMapper` classes to map the `displayOrder` field from the request DTO to the corresponding domain entity.
3. Refactored the `createLesson` and `createModule` methods in the `LessonServiceImpl` and `ModuleServiceImpl` classes, respectively, to use the corresponding mappers to create the domain entities from the request DTOs.
These changes improve the validation and mapping of the `displayOrder` field, ensuring that the display order is a positive number and that it is …
=> feat(lesson): add display order validation and mapping

.idea/vcs.xml, Cargo.toml
This pull request upgrades the Tauri dependency from version 2.0.6 to 2.1.0. Additionally, it fixes the issue with drag-and-drop functionality for images on the Linux platform. The upgrade to Tauri 2.1.0 resolves the problem we had with the drag-n-drop event not including the path to the image on Linux.
=> chore: Upgrade Tauri dependency to 2.1.0

apps/desktop/src-tauri/src/lib.rs, apps/desktop/src/app.vue, apps/desktop/src/layouts/default.vue
1. **Refactor app and layout components**: The `app.vue` and `default.vue` components have been refactored to improve the organization and separation of concerns. The update-related logic and UI have been moved from `app.vue` to `default.vue`, as the update functionality is more closely tied to the layout than the app itself. Additionally, the unused `useUserStore` and `useUpdater` imports have been removed from `app.vue`, and the `UpdateModal` component has been removed from `app.vue` as it is now included in the `default.vue` layout.
2. **Add debug logging and improve splashscreen handling**: This change adds debug logging to the `close_splashscreen_show_main` command and improves the handling of the splashscreen window. The main changes …
=> remove-update-modal

apps/desktop/src-tauri/src/lib.rs, apps/desktop/src-tauri/src/window.rs, apps/desktop/src-tauri/tauri.conf.json, apps/desktop/src/pages/splashscreen.vue
This commit refactors the window management in the Tauri application. The
main changes are:
1. Moved the window creation and management logic to a dedicated
`WindowManager` module.
2. Simplified the `tauri.conf.json` file by removing the window
configurations and handling them programmatically in the
`WindowManager`.
3. Added support for window effects (e.g., acrylic effect) on Windows.
4. Implemented a `handle_window_transition` function to handle the
transition from the splashscreen to the main window.
These changes improve the maintainability and flexibility of the window
management in the application.
=> feat(tauri): Refactor window management

apps/desktop/src-tauri/src/lib.rs, apps/desktop/src-tauri/src/window.rs
Fixes the Mutex import in `lib.rs` by removing an extraneous character.  
Updates the color instantiation in `window.rs` to use the correct  
constructor format for the Color struct. These changes ensure proper  
functionality and adherence to the code standards.
=> ✨ fix: correct Mutex import and color instantiation

apps/desktop/package.json, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/capabilities/default.json, apps/desktop/src-tauri/src/lib.rs, pnpm-lock.yaml
The changes in this commit remove the `tauri-plugin-window-state` plugin from the Tauri application. This plugin was previously used to save and restore the state of the application window, but it is no longer needed. The removal of this plugin simplifies the application's dependencies and reduces the overall complexity of the codebase.
=> feat(desktop): remove unused window state plugin

apps/desktop/package.json, apps/desktop/src-tauri/crates/common/Cargo.toml, apps/desktop/src-tauri/crates/common/src/lib.rs, apps/desktop/src-tauri/crates/education/src/courses/commands/mod.rs, apps/desktop/src-tauri/crates/education/src/courses/mod.rs, apps/desktop/src-tauri/crates/education/src/lib.rs, apps/desktop/src-tauri/crates/education/src/modules/commands/mod.rs, apps/desktop/src-tauri/crates/education/src/modules/mod.rs, apps/desktop/src-tauri/crates/education/src/roadmaps/commands/mod.rs, apps/desktop/src-tauri/crates/education/src/roadmaps/mod.rs, apps/desktop/src/components/education/ContentForm.vue, apps/desktop/src/components/roadmap/RoadmapForm.vue, apps/desktop/src/composables/index.ts, apps/desktop/src/composables/useEducationalContent.ts, apps/desktop/src/composables/useEducationalForm.ts, apps/desktop/src/composables/useImageDrop.ts, apps/desktop/src/pages/admin/roadmaps/create.vue, apps/desktop/src/types/education-commands.interface.ts, apps/desktop/src/types/index.ts, pnpm-lock.yaml
This pull request introduces the following changes:
1. Added the `@types/turndown` and `turndown` dependencies to the project.
2. Added the `log` crate to the common module's dependencies, providing logging capabilities for better debugging and error handling.
3. Implemented support for uploading roadmap images. The `upload_roadmap_image_command` function now accepts the image path and alt text, and uses the `handle_content_image_upload` function to handle the image upload process.
4. The `handle_content_image_upload` function is a generic function that can be used to upload images for different types of content, such as roadmaps, modules, etc. It handles the image validation, file size check, and API request to upload the image.
5. Removed the unused `upload_module_image` function, as …
=> feat(desktop): Create Roadmaps

apps/backend/core/src/main/java/com/cortex/backend/core/common/SortUtils.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapController.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapRepository.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapService.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapServiceImpl.java, apps/desktop/src/pages/exercises/index.vue, bruno/Education/Roadmap/Get All Published Roadmaps.bru, bruno/Education/Roadmap/Get All Roadmaps.bru
This pull request introduces the following changes:
1. Improved exercise fetching and error handling:
- Removed unnecessary console logs
- Improved error handling when fetching exercises to ensure proper data display and better debugging
2. Implemented a new `SortUtils` class in the `core` module:
- Provides functionality for parsing and validating sort parameters
- Allows for dynamic sorting of data based on client-provided sort parameters
3. Added sorting to the roadmap retrieval endpoints:
- Modified the `RoadmapService` interface to accept a `String[]` parameter for sorting
- Implemented the sorting logic in the `RoadmapServiceImpl` class using the `SortUtils` utility
- Updated the `RoadmapController` to accept the `sort` parameter and pass it to the service methods
- Added a new …
=> feat(education/roadmap): Add sorting to roadmap APIs

.idea/vcs.xml, apps/backend/core/src/main/java/com/cortex/backend/core/domain/User.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapController.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapRepository.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapService.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapServiceImpl.java, apps/desktop/src-tauri/crates/common/src/lib.rs, apps/desktop/src-tauri/crates/education/src/roadmaps/commands/mod.rs, apps/desktop/src-tauri/crates/education/src/roadmaps/mod.rs, apps/desktop/src-tauri/crates/error/src/lib.rs, apps/desktop/src/composables/useRoadmaps.ts, apps/desktop/src/pages/explore/index.vue, packages/shared/components/roadmaps/RoadmapCard.vue, packages/shared/components/roadmaps/RoadmapList.vue, packages/shared/types/education.interface.ts, packages/shared/types/index.ts, packages/shared/types/sort-params.interface.ts
This pull request introduces several improvements and new features to the roadmap functionality in the application:
1. **Add SortQueryParams interface**: A new `SortQueryParams` interface has been added to the `shared/types` module, which defines the parameters used for sorting and pagination in API requests.
2. **Remove unused code execution interfaces**: The unused `CodeExecutionRequest`, `CodeExecutionSubmissionResponse`, `TestCaseResult`, and `CodeExecutionResult` interfaces have been removed from the `education.interface.ts` file.
3. **Add hasAnyRole method to User entity**: A new `hasAnyRole` method has been added to the `User` entity, which checks if the user has any of the specified roles. This is useful for authorization checks in the application.
4. **Add …
=> feat(roadmaps): add sort options

apps/desktop/src/types/education-commands.interface.ts
The roadmap redirect path is updated from `/roadmaps` to `/explore` to
better align with the application's navigation structure and user
experience.
=> feat(education): update roadmap redirect path

apps/desktop/src/components/tiptap/EditorBubbleMenu.vue, apps/desktop/src/components/tiptap/EditorToolbar.vue
The changes add the `type="button"` attribute to all the buttons in the Tiptap editor components. This ensures that the buttons behave correctly and prevent unexpected form submission behavior.
=> fix (roadmaps): fix form submitting when clicking on other buttons

apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/LessonController.java
Adds a `@PreAuthorize` annotation to the `LessonController#getAdminLessons`
endpoint, restricting access to only users with the `MODERATOR` or `ADMIN`
roles. This change ensures that the lesson list in the admin interface is
only accessible to authorized users.
=> feat(lessons): Add admin-only access to lesson list

apps/backend/auth/src/main/java/com/cortex/backend/auth/internal/PKCEAwareOAuth2SuccessHandler.java, apps/backend/core/src/main/java/com/cortex/backend/core/domain/User.java, apps/desktop/src/pages/auth/login.vue, apps/desktop/src/stores/auth.store.ts
This pull request introduces the following changes:
1. **Redirect desktop clients with incomplete profiles**: The `PKCEAwareOAuth2SuccessHandler` class has been updated to handle desktop clients with incomplete user profiles. If the user's profile is not complete, the handler will redirect the client to the same redirect URI, but with additional query parameters indicating that the profile is incomplete and needs to be updated.
2. **Implement OAuth login flow for desktop app**: The `loginWithProviderDesktop` function in the `auth.store.ts` file has been refactored to handle the OAuth login flow more robustly. This includes adding a timeout to the login process, handling the case where the user needs to complete their profile after logging in, and cleaning up the listener and port when the …
=> fix(oauth): fix incomplete profile breaking the desktop app

packages/shared/components/CodeEditor.vue, packages/shared/composables/editor/useEditorExtensions.ts
This commit adds a new `lineWrapping` prop to the `CodeEditor` component and the `useEditorExtensions` composable. This allows users to enable or disable line wrapping in the code editor.
The changes include:
- Add `lineWrapping` prop to the `CodeEditor` component with a default value of `true`.
- Update the `useEditorExtensions` composable to include the `lineWrapping` option and add the `lineWrappingExtension` to the list of extensions if `lineWrapping` is enabled.
- Update the type definition for the `useEditorExtensions` function to include the `lineWrapping` option.
These changes provide more flexibility for users to customize the code editor's behavior and improve the overall user experience.
=> feat(CodeEditor): add line wrapping option

apps/frontend/nuxt.config.ts
Add configuration for Material Design Components (MDC) in the Nuxt 
application. This includes custom component mappings for prose 
elements, disabling anchor links for headings, and setting up syntax 
highlighting with a specific theme and language support. These changes
=> ✨ feat: add Material Design Components configuration

apps/backend/core/src/main/java/com/cortex/backend/core/common/BusinessErrorCodes.java, apps/backend/core/src/main/java/com/cortex/backend/core/common/exception/AlreadyEnrolledException.java, apps/backend/core/src/main/java/com/cortex/backend/core/domain/EnrollmentStatus.java, apps/backend/core/src/main/java/com/cortex/backend/core/domain/RoadmapEnrollment.java, apps/backend/core/src/main/java/com/cortex/backend/core/domain/RoadmapEnrollmentId.java, apps/backend/core/src/main/java/com/cortex/backend/core/handler/GlobalExceptionHandler.java, apps/backend/education/src/main/java/com/cortex/backend/education/progress/api/RoadmapEnrollmentEvent.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapController.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapEnrollmentRepository.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapService.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/dto/RoadmapEnrollmentRequest.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/dto/RoadmapEnrollmentResponse.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapEnrollmentMapper.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapEnrollmentService.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapServiceImpl.java, bruno/Education/Roadmap/Enroll.bru, bruno/Education/Roadmap/Enrollments.bru
This commit introduces the `EnrollmentStatus` enum and the `RoadmapEnrollment` entity to the backend application. The changes include:
- Added the `EnrollmentStatus` enum with values `ACTIVE`, `PAUSED`, `DROPPED`, and `COMPLETED`.
- Created the `RoadmapEnrollment` entity to store information about a user's enrollment in a roadmap, including the enrollment date, status, and last activity date.
- Implemented the `RoadmapEnrollmentMapper` to map the `RoadmapEnrollment` entity to a `RoadmapEnrollmentResponse` DTO.
- Updated the `RoadmapServiceImpl` to use the new `RoadmapEnrollment` entity when retrieving roadmap courses.
- Added the `AlreadyEnrolledException` exception to handle cases where a user is already enrolled in a roadmap.
- Updated the `GlobalExceptionHandler` to handle the …
=> feat(enrollment): add enrollment status and roadmap enrollment entity

apps/backend/user/src/main/java/com/cortex/backend/user/api/UserController.java, bruno/User/Get User By Email.bru
This commit adds a new endpoint to the UserController that allows
retrieving a user by their email address. The endpoint is secured
with the MODERATOR and ADMIN roles, and it returns a UserResponse
object containing the user's details.
The new endpoint is implemented in the getUserByEmail method, which
takes an email parameter and uses the userService to fetch the user
by email. If the user is found, it is returned in the response,
otherwise a 404 Not Found exception is thrown.
=> feat(user): Add endpoint to retrieve user by email

apps/backend/app/src/main/java/com/cortex/backend/Application.java, apps/backend/app/src/main/java/com/cortex/backend/config/TransactionConfig.java, apps/backend/core/src/main/java/com/cortex/backend/core/common/BusinessErrorCodes.java, apps/backend/core/src/main/java/com/cortex/backend/core/common/exception/InvalidExerciseStateException.java, apps/backend/core/src/main/java/com/cortex/backend/core/handler/GlobalExceptionHandler.java, apps/backend/education/src/main/java/com/cortex/backend/education/course/api/CourseRepository.java, apps/backend/education/src/main/java/com/cortex/backend/education/course/api/CourseService.java, apps/backend/education/src/main/java/com/cortex/backend/education/course/internal/CourseServiceImpl.java, apps/backend/education/src/main/java/com/cortex/backend/education/exercise/api/ExerciseRelationResolver.java, apps/backend/education/src/main/java/com/cortex/backend/education/progress/api/ProgressTrackingService.java, apps/backend/education/src/main/java/com/cortex/backend/education/progress/internal/EntityRelationService.java, apps/backend/education/src/main/java/com/cortex/backend/education/progress/internal/ProgressTrackingServiceImpl.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapEnrollmentService.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapServiceImpl.java, apps/backend/engine/src/main/java/com/cortex/backend/engine/api/EngineController.java, apps/backend/engine/src/main/java/com/cortex/backend/engine/internal/ExerciseRelationResolverImpl.java, apps/backend/engine/src/main/java/com/cortex/backend/engine/internal/services/CodeExecutionService.java
The changes in this commit include:
1. Added a new method `trackProgressAndCheckCompletion` in the `ProgressTrackingService` interface to track the progress of a user for a given exercise and check if the lesson is completed.
2. Created a new interface `ExerciseRelationResolver` with methods to get the lesson ID for a given exercise and check if all exercises for a lesson are completed by a user.
3. Refactored the `EngineController` to handle exceptions more gracefully and return appropriate HTTP status codes.
4. Removed the unused `@Transactional` annotation from the `Application` class.
5. Added a new `TransactionConfig` class to configure a `TransactionTemplate` with a `REQUIRES_NEW` propagation behavior.
=> feat(progress-tracking): Add new method to track progress and check completion

apps/backend/app/src/main/resources/application-dev.yml
Adds the `user:email` and `read:user` scopes to the GitHub OAuth2
configuration. This allows the application to retrieve the user's email
address and basic profile information during the authentication flow.
=> feat(auth): Add GitHub OAuth2 scopes for email and user info

apps/backend/chat/src/main/java/com/cortex/backend/chat/api/AiChatController.java, apps/backend/chat/src/main/java/com/cortex/backend/chat/config/AiConfig.java, apps/backend/chat/src/main/java/com/cortex/backend/chat/internal/AiChatService.java, bruno/Exercise/Result.bru
The changes made in this commit include:
1. Modify the `getChatStream` method in `AiChatService` to accept a `username` parameter, which is used to identify the conversation in the chat memory.
2. Update the `ChatClient` configuration in `AiConfig` to use the `PromptChatMemoryAdvisor` in addition to the `MessageChatMemoryAdvisor`. This allows the chat memory to be used for both the user's messages and the AI's responses.
3. Enhance the chat memory configuration by setting the `CHAT_MEMORY_CONVERSATION_ID_KEY` to the `username` and the `CHAT_MEMORY_RETRIEVE_SIZE_KEY` to 100, which determines the number of previous messages to consider in the chat memory.
These changes aim to improve the chat experience by maintaining a conversation context and allowing the AI to provide more relevant and …
=> feat(chat): Add username to chat stream and improve chat memory

apps/backend/chat/src/main/java/com/cortex/backend/chat/api/AiChatController.java, apps/backend/chat/src/main/java/com/cortex/backend/chat/internal/AiChatService.java
Removes the `username` parameter from the `getChatStream` method in the
`AiChatService` class. The `username` parameter was previously used to set
the `CHAT_MEMORY_CONVERSATION_ID_KEY` parameter in the chat client, but
this has been changed to use the `exerciseSlug` instead. This change
simplifies the method signature and removes the need to pass the
`Authentication` object from the controller to the service.
=> fix(chat): Remove username parameter from getChatStream

apps/backend/education/src/main/java/com/cortex/backend/education/achievement/internal/AchievementProcessorServiceImpl.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/LessonController.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/LessonService.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/dto/ExerciseInfo.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/dto/LessonResponse.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/internal/LessonMapper.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/internal/LessonServiceImpl.java
The changes made in this commit include:
1. Added the `Authentication` parameter to the `getLessonById` and `getLessonBySlug` methods in the `LessonController` class. This allows the controller to retrieve the user's ID from the authentication object and pass it to the service layer.
2. Updated the `getLessonById` and `getLessonBySlug` methods in the `LessonServiceImpl` class to accept the user ID and use it to retrieve the user's progress for the lesson.
3. Modified the `toLessonResponse` method in the `LessonMapper` interface to include the user's progress for the lesson.
4. Added the `getUserProgress` method to the `LessonResponse` class to retrieve the user's progress for the lesson.
These changes were made to enhance the lesson response by including the user's progress for the …
=> feat(lesson): add user progress to lesson response

Cargo.toml, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/dto/ExerciseInfo.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/internal/LessonMapper.java, apps/desktop/src-tauri/crates/education/Cargo.toml, apps/desktop/src-tauri/crates/education/src/lib.rs, apps/desktop/src-tauri/crates/education/src/roadmaps/commands/mod.rs, apps/desktop/src-tauri/crates/education/src/roadmaps/mod.rs, apps/desktop/src-tauri/src/lib.rs
1. **Add display order to exercise info**: Adds a new `displayOrder` field to the `ExerciseInfo` DTO to represent the order in which the exercises should be displayed. This change is necessary to ensure the exercises are presented to the user in the correct order.
2. **Add chrono dependency**: The changes in this commit add the `chrono` dependency to the `education` crate in the Tauri desktop application. This dependency is required to handle date and time-related functionality within the application.
3. **Add enroll_in_roadmap command**: This commit adds a new Tauri command `enroll_in_roadmap` to the education module. This command allows users to enroll in a specific roadmap by providing the roadmap ID.
The changes include:
- Adding a new …
=> feat(roadmaps): enroll funcionality

apps/desktop/package.json, package.json, pnpm-lock.yaml
The changes in this commit update the dependencies in the `pnpm-lock.yaml` file. The key changes are:
- Update the `@codemirror/view` dependency from `6.34.2` to `6.34.3`.
- Update the `@typescript-eslint/typescript-estree` and `@typescript-eslint/utils` dependencies to the latest version `8.14.0`.
- Update the `@typescript-eslint/visitor-keys` dependency to the latest version `8.14.0`.
- Update the `@tauri-apps/api` dependency from `2.1.0` to `2.1.1`.
- Update the `@tauri-apps/cli-*` dependencies to the latest version `2.1.0`.
These updates are necessary to ensure the project is using the latest versions of the dependencies, which may include bug fixes, performance improvements, or new features.
=> feat(pnpm-lock): update dependencies

Cargo.toml, apps/desktop/src-tauri/crates/education/src/lib.rs, apps/desktop/src-tauri/crates/education/src/roadmaps/commands/mod.rs, apps/desktop/src-tauri/crates/education/src/roadmaps/mod.rs
1. **Add 'test' feature to Tauri dependency**: The changes in this commit add the 'test' feature to the Tauri dependency in the Cargo.toml file. This is done to enable testing functionality for the Tauri application.
2. **Add custom datetime serialization and deserialization**: This change adds custom serialization and deserialization for `DateTime<Utc>` types in the `RoadmapEnrollmentResponse` struct. This ensures that the datetime fields are properly formatted and parsed when working with the `education` crate.
3. **Add get_user_enrollments command**: This change adds a new Tauri command `get_user_enrollments` to the `education` crate. The command fetches the user's current roadmap enrollments from the API and returns them as a …
=> feat(roadmap): add  get_user_enrollments command

apps/desktop/src-tauri/crates/ai_chat/src/providers/gemini.rs, apps/desktop/src/components/ai/ModelSelector.vue, apps/desktop/src/components/ai/chat.vue, apps/desktop/src/composables/useDesktopErrorHandler.ts, apps/desktop/src/pages/exercises/[id]/solve.vue
1. **Handle Gemini API errors and improve usage tracking**:
- Adds error handling for Gemini API responses, specifically when the `candidatesTokenCount` field is missing from the JSON response.
- Improves the tracking of token usage by summing the `candidates_token_count` across all response candidates.
- Updates the `UsageMetadata` struct to include the total candidates token count.
2. **Add error handling and UI improvements to the chat component**:
- Adds an `isChatBlocked` computed property that checks if the chat is in a state where it should be disabled (e.g., when there's an error, the user is sending a message, or the AI is streaming a response).
- Modifies the `sendMessage` function to use the `isChatBlocked` computed property to …
=> fix: handle gemini errors

apps/desktop/src-tauri/crates/education/src/lib.rs
Adds the `display_order` field to `RoadmapLesson` and `RoadmapModule` 
structs to enable custom ordering of lessons and modules. This change 
improves the flexibility of the roadmap structure, allowing for better 
presentation and organization of educational content. The `display_order` 
field is commented out in `RoadmapCourse` for future use.
=> ✨ feat: add display_order to roadmap structures

apps/frontend/src/pages/about.vue, apps/frontend/src/pages/auth/login.vue
The changes made in this commit include:
1. Adding `definePageMeta` to the `about.vue` file, which sets the `auth` property to `false`. This ensures that the about page is accessible to both authenticated and unauthenticated users.
2. Updating the `navigateAuthenticatedTo` property in the `login.vue` file from `/roadmaps` to `/explore`. This change ensures that authenticated users are redirected to the `/explore` page after successful login, instead of the `/roadmaps` page.
=> feat(pages): add auth metadata to about page and update login redirect

apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/RoadmapRepository.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/dto/RoadmapDetails.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/api/dto/RoadmapMentorDTO.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapMapper.java, apps/backend/education/src/main/java/com/cortex/backend/education/roadmap/internal/RoadmapServiceImpl.java
This change adds the ability to retrieve mentor details for a roadmap. The
RoadmapMapper now includes a new method `userToMentorDto` that maps a user
entity to a RoadmapMentorDTO. This DTO contains the mentor's full name,
username, and avatar URL.
The RoadmapServiceImpl has been updated to pass the UserRepository to the
RoadmapMapper when retrieving the roadmap details, allowing the mapper to
fetch the mentor information.
Additionally, the RoadmapRepository has been updated to use a more readable
query for fetching the roadmap details with the admin role.
=> feat(roadmap): Add mentor details to roadmap response

apps/desktop/src-tauri/crates/education/src/lib.rs, apps/desktop/src/composables/useRoadmaps.ts, apps/desktop/src/pages/explore/[slug]/index.vue, packages/shared/components/roadmaps/RoadmapOverview.vue
**Pull Request Description:**
This pull request adds mentor details to the roadmap overview in the application. The changes include:
1. Exporting the `enrollments` function from the `useRoadmaps` composable, which allows it to be used in other parts of the application when working with roadmaps.
2. Displaying the mentor information, including the full name, username, and avatar image, on the roadmap card in the explore page. This provides users with more detailed information about the roadmap they are viewing.
3. Adding the mentor details to the roadmap overview component, which now displays the mentor's full name, username, and avatar image to provide more context about the roadmap's mentor.
These changes enhance the user experience by giving users more information about the roadmaps …
=> add-mentor-details-to-roadmap-overview

apps/frontend/src/stores/auth.store.ts
Simplify the account activation endpoint by removing the
unnecessary "/auth" segment from the URL. This change makes
the endpoint more concise and easier to maintain.
=> 🔒 feat(auth): Simplify account activation endpoint

apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/tauri.conf.json
Bumps the version number in the `tauri.conf.json` and `Cargo.toml` files
from 0.1.6 to 0.1.7. This change is necessary to reflect the latest
version of the Cortex Desktop Application for Premium Users.
=> 🔖 feat(version): Bump version to 0.1.7

apps/desktop/src/pages/admin/roadmaps/[slug].vue
Improves the loading state handling in the admin roadmaps page. When the
page is in create mode, the loading state is set to false to avoid
showing a loading spinner. When the page is in edit mode, the loading
state is set to the value of the `loading` variable.
=> 🎨 feat(admin/roadmaps): improve loading state handling

apps/backend/core/src/main/java/com/cortex/backend/core/common/BusinessErrorCodes.java, apps/backend/core/src/main/java/com/cortex/backend/core/common/exception/FailedToActivateLicenseException.java, apps/backend/core/src/main/java/com/cortex/backend/core/common/exception/FailedToDeactivateLicenseException.java, apps/backend/core/src/main/java/com/cortex/backend/core/common/exception/FailedToValidateLicenseException.java, apps/backend/core/src/main/java/com/cortex/backend/core/handler/GlobalExceptionHandler.java, apps/backend/payments/src/main/java/com/cortex/backend/payments/api/SubscriptionsController.java, apps/backend/payments/src/main/java/com/cortex/backend/payments/internal/PaymentsService.java, bruno/Payments/Deactivate License Key.bru, bruno/Payments/Validate License Key.bru
Adds new exceptions and error codes for handling license-related operations:
- `FailedToActivateLicenseException`
- `FailedToValidateLicenseException`
- `FailedToDeactivateLicenseException`
These exceptions are used in the `PaymentsService` to handle failures during license activation, validation, and deactivation.
The `GlobalExceptionHandler` is updated to handle these new exceptions and provide appropriate HTTP responses.
=> ✨ feat(license): add license activation, validation, and deactivation

apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/LessonController.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/LessonRepository.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/api/LessonService.java, apps/backend/education/src/main/java/com/cortex/backend/education/lesson/internal/LessonServiceImpl.java, bruno/Education/Lesson/Get Lesson By Module.bru
This change adds a new endpoint to the LessonController that allows retrieving lessons by a given module ID. The LessonService and LessonRepository have been updated to support this new functionality.
The main changes are:
- Added a new `getLessonsByModule` method in the LessonService interface and its implementation in LessonServiceImpl.
- Added a new `findAllByModule` method in the LessonRepository to fetch lessons by module ID.
- Added a new `getLessonByModuleId` endpoint in the LessonController to handle the new functionality.
=> ✨ feat(lesson): Add endpoint to get lessons by module
